### PR TITLE
Add checks for cuda to make software run without GPU

### PR DESCRIPTION
**Pull request by jotsif**

### CODE REVIEW

**Comment by YacobBY** [comment]
Hey,

I was doing this myself a while back but since I wasn't feeling like pulling my GPU out or testing this on another system I kind of let it go because I didn't know if it would work well.

Instead of using big if/else statements you can define a device which is the CPU or GPU
`device = torch.device("cuda" if torch.cuda.is_available() else "cpu") `  
and  rewrite every `.cuda() `function to `.to(device')`

**Comment by jotsif** [comment]
Sure thing, just wanted to follow how the code was written already.

**Comment by mahendra047** [comment]
Hi, you need to change two more file /modules/prediction.py , line 18, 32,33,34,46,47  and /modules/transformation.py", line 152 to make software run without GPU.  i tested demo.py after updating these two files its working fine.

**Comment by ku21fan** [comment]
@soldierofhell Hello,
Thank you for the pull request. 
I just updated related codes as suggested by @YacobBY @mahendra047. 8f7255fb4b177b3f5c47df9cdec7649c0a08469e

Thank you :)

**Pull request closed without merging**
